description: The item entity for Produce objects
type: object
properties:
  name:
    type: string
    minLength: 1
  quantity:
    type: number
  size:
    type: string
    minLength: 1
required:
  - name
  - quantity
  - size
x-examples:
  example-1:
    name: Potato
    quantity: 1000
    size: Miniature
